function battery_idx()
    BATTERY_ID=2;
    BATTERY_INSERVICE=3;
    BATTERY_CONNECTED_BUS=5;
    BATTERY_CELLS=6;
    BATTERY_PACKS=7;
    BATTERY_STRINGS=8;
    return BATTERY_ID,BATTERY_INSERVICE,BATTERY_CONNECTED_BUS,BATTERY_CELLS,BATTERY_PACKS,BATTERY_STRINGS
end