function dcimp_idx()
    DC_IMPEDANCE_ID=2;
    DC_IMPEDANCE_INSERVICE=3;
    DC_IMPEDANCE_F_ELEMENT=5;
    DC_IMPEDANCE_T_ELEMENT=6;
    DC_IMPEDANCE_R=7;
    DC_IMPEDANCE_L=8;
    return DC_IMPEDANCE_ID,DC_IMPEDANCE_INSERVICE,DC_IMPEDANCE_F_ELEMENT,DC_IMPEDANCE_T_ELEMENT,DC_IMPEDANCE_R,DC_IMPEDANCE_L
end