function dcload_idx()
    DCLOADID=2;
    DCLOADINSERVICE=3;
    DCLOADCONNECTEDBUS=5;
    DCLOADRATEDV=6;
    DCLOADKW=7;
    DCLOADPERCENTP=8;
    DCLOADPERCENTZ=9;
    return DCLOADID,DCLOADINSERVICE,DCLOADCONNECTEDBUS,DCLOADRATEDV,DCLOADKW,DCLOADPERCENTP,DCLOADPERCENTZ
end