function XFORM3W_idx()
    #三相变压器索引
    ##===================================idx=========================##
    XFORM3W_ID=2;#设备ID
    XFORM3W_INSERVICE=3;#是否投入运行
    XFORM3W_STATE=4;#变压器状态
    XFORM3W_PRI_ELEMENT=5;#高压侧母线
    XFORM3W_SEC_ELEMENT=6;#低压侧母线
    XFORM3W_TERT_ELEMENT=7;#中性点母线
    XFORM3W_PRI_KV =8;#高压侧电压
    XFORM3W_SEC_KV =9;#低压侧电压
    XFORM3W_TERT_KV =10;#中性点电压
    XFORM3W_PRI_TAP=11;#高压侧变比
    XFORM3W_SEC_TAP=12;#低压侧变比
    XFORM3W_TERT_TAP=13;#中性点变比
    XFORM3W_PRI_KVA=14;#高压侧额定容量
    XFORM3W_SEC_KVA=15;#低压侧额定容量
    XFORM3W_TERT_KVA=16;#中性点额定容量
    XFORM3W_PRI_POSZ=17;#高压侧正序阻抗
    XFORM3W_PRI_X_R = 18;#高压侧正序电抗
    XFORM3W_SEC_POSZ=19;#低压侧正序阻抗
    XFORM3W_SEC_X_R = 20;#低压侧正序电抗
    XFORM3W_TERT_POSZ=21;#中性点正序阻抗
    XFORM3W_TERT_X_R = 22;#中性点正序电抗

    return XFORM3W_ID,XFORM3W_INSERVICE,XFORM3W_STATE,XFORM3W_PRI_ELEMENT,XFORM3W_SEC_ELEMENT,XFORM3W_TERT_ELEMENT,XFORM3W_PRI_KV,XFORM3W_SEC_KV,XFORM3W_TERT_KV,XFORM3W_PRI_TAP,XFORM3W_SEC_TAP,XFORM3W_TERT_TAP,XFORM3W_PRI_KVA,XFORM3W_SEC_KVA,XFORM3W_TERT_KVA,XFORM3W_PRI_POSZ,XFORM3W_PRI_X_R,XFORM3W_SEC_POSZ,XFORM3W_SEC_X_R,XFORM3W_TERT_POSZ,XFORM3W_TERT_X_R
end